### ISSUE TITLE
Support to pass parameters to the AWS IoT Fleet Provisioning RegisterThing MQTT request

### ISSUE THREAD

**Issue by janborch** [awslabs/aws-iot-device-client#100]
The AWS IoT Fleet provisioning flow allows to pass parameter in the payload to the RegisterThing request as explained here:
https://docs.aws.amazon.com/iot/latest/developerguide/fleet-provision-api.html#register-thing
This parameter can be used to pass device information to the Provisioning template to customize the resources created. A common scenario is to pass a device serial number as parameter and use this to create the ThingName or add as an Thing attribute.

```json
{
    "certificateOwnershipToken": "string",
    "parameters": {
        "serialNumber": "1234455",
        ...
    }
}
```
A possible implementation would be to add a parameter object to the fleet provisioning config section (and/or pass it using the command line):

```json
...
 "fleet-provisioning": {
    "enabled": true,
    "template-name": "MyTemplate",
    "csr-file": "/var/key/device.csr",
    "parameters": {
          "serial" : "1234567"
    }
  }
```

**Comment by HarshGandhi-AWS** [comment]
Hello @janborch ,

Thank you for suggesting us this enhancement in Fleet Provisioning feature. @doronbl [here](https://github.com/awslabs/aws-iot-device-client/pull/130) has provided a solution to pass parameters from device to AWS IoT Fleet Provisioning while registering the device. We have reviewed and tested his changes before merging it and it looks like this should resolve your issue. 
I am closing this issue now, please feel free to reopen this issue or create a new one if required.

Again thank you @doronbl for your contribution and @janborch for suggesting us this enhancement in Fleet Provisioning feature.

Regards,
Harsh Gandhi
