### ISSUE TITLE
When using Fleet provisioning with a CSR the runtime config points to the wrong private key (bootstrap cert key)

### ISSUE THREAD

**Issue by janborch** [awslabs/aws-iot-device-client#101]
I use the following device client config file, where I point to my bootstrapping cert and key files in the main section. In the fleet provisioning section I reference a CSR I generated from a newly generated device key.

```json
{
  "endpoint": "xxxxxxxxxx-ats.iot.eu-west-1.amazonaws.com",
  "cert": "/home/ubuntu/adc/bootstrap.pem",
  "key": "/home/ubuntu/adc/bootstrap.key",
  "root-ca": "/home/ubuntu/adc/AmazonRootCA1.pem",
  "thing-name": "UbuntuEC201",
  "logging": {
    "level": "DEBUG",
    "type": "FILE",
    "file": "/var/log/aws-iot-device-client/aws-iot-device-client.log"
  },
  "jobs": {
    "enabled": true,
    "handler-directory": "/home/ubuntu/adc/handler"
  },
  "tunneling": {
    "enabled": true
  },
  "device-defender": {
    "enabled": true,
    "interval": 60
  },
  "fleet-provisioning": {
    "enabled": true,
    "template-name": "ProvisioningTemplate-bad1wpiFF6M0",
    "csr-file": "/home/ubuntu/adc/deviceec201.csr"
  }
}
```

The provisioning succeeds and the following runtime config is generated, but the `key` entry points to the wrong key. It should point to my device key not the bootstrap key.
```json
{
"runtime-config": {
    "completed-fp": true,
    "cert": "/root/.aws-iot-device-client/keys/d65e7933fd7b363071a737d4be24d28d8f3614d9aea17f6dd72839ac2c1d560b-certificate.pem.crt",
    "key": "/home/ubuntu/adc/bootstrap.key",
    "thing-name": "ThingFP-d65e7933fd7b363071a737d4be24d28d8f3614d9aea17f6dd72839ac2c1d560b"
    }
}
```
Additionally when you restart the client with this wrong config the client terminates with a segmentation fault.

## Expected runtime config:

I should be able to provide my device key location along the device CSR location in the config file 

```json
...
  "fleet-provisioning": {
    "enabled": true,
    "template-name": "ProvisioningTemplate-bad1wpiFF6M0",
    "csr-file": "/home/ubuntu/adc/deviceec201.csr",
    "key": "/home/ubuntu/adc/deviceec201.key"
  }
```

and the generated runtim-config file should point to the device key not the bootstrap key:

```json
{
"runtime-config": {
    "completed-fp": true,
    "cert": "/root/.aws-iot-device-client/keys/d65e7933fd7b363071a737d4be24d28d8f3614d9aea17f6dd72839ac2c1d560b-certificate.pem.crt",
    "key": "/home/ubuntu/adc/deviceec201.key",
    "thing-name": "ThingFP-d65e7933fd7b363071a737d4be24d28d8f3614d9aea17f6dd72839ac2c1d560b"
    }
}
```

**Comment by matthewpaul** [comment]
Thanks for submitting this issue @janborch! We are actively investigating this one. In the meantime, do you have any additional information regarding the segmentation fault that you experienced? It would be helpful if you can provide us with the any of the following information:

- AWS IoT Device Client Version (should be available from your logs)
- Host Platform Information (Hardware, OS, Kernel Version info)
- Compilation Information (How/where was your Device Client compiled?)
- Core dump/crash info if available
- Sanitized Device Client/SDK logs if available/relevant

**Comment by janborch** [comment]
Here additional info on the segmentation fault:

+ AWS IoT Device Client version v1.0.9
+ Ubuntu 20.04.1 LTS (EC2)
+ Linux ip-192-168-11-161 5.4.0-1029-aws #30-Ubuntu SMP Tue Oct 20 10:06:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
+ cmake : 3.16.3-1ubuntu1
+ build-essential 12.8ubuntu1

## Log files
[coredump.txt](https://github.com/awslabs/aws-iot-device-client/files/5882717/coredump.txt)
[aws-iot-device-client.log](https://github.com/awslabs/aws-iot-device-client/files/5882722/aws-iot-device-client.log)

## Compiled with following commands
```
sudo apt-get update
sudo apt install build-essential
sudo apt-get install cmake 
sudo apt-get install libssl-dev

git clone https://github.com/awslabs/aws-iot-device-client.git

cd aws-iot-device-client
mkdir build
cd build
cmake ../
cmake --build . --target aws-iot-device-client

sudo ./aws-iot-device-client --config-file /home/ubuntu/config.json
```

## Config file

```
{
    "endpoint": "xxxxxxxxxxx-ats.iot.eu-west-1.amazonaws.com",
    "cert": "/home/ubuntu/adc/bootstrap.pem",
    "key": "/home/ubuntu/adc/bootstrap.key",
    "root-ca": "/home/ubuntu/adc/AmazonRootCA1.pem",
    "thing-name": "UbuntuEC201",
    "logging": {
        "level": "DEBUG",
        "type": "FILE",
        "file": "/var/log/aws-iot-device-client/aws-iot-device-client.log"
     },
    "jobs": {
        "enabled": true,
        "handler-directory": "/home/ubuntu/adc/handler"
    },
    "tunneling": {
        "enabled": true
    },
    "device-defender": {
        "enabled": true,
        "interval": 60 
    },
    "fleet-provisioning": {
        "enabled": true,
        "template-name": "ProvisioningTemplate-bad1wpiFF6M0",
        "csr-file": "/home/ubuntu/adc/device01.csr"
    }
}
```
runtime-config

```
{
"runtime-config": {
    "completed-fp": true,
    "cert": "/root/.aws-iot-device-client/keys/d65e7933fd7b363071a737d4be24d28d8f3614d9aea17f6dd72839ac2c1d560b-certificate.pem.crt",
    "key": "/home/ubuntu/adc/bootstrap.key",
    "thing-name": "ThingFP-d65e7933fd7b363071a737d4be24d28d8f3614d9aea17f6dd72839ac2c1d560b"
    }
}
```

**Comment by matthewpaul** [comment]
@janborch while we are still investigating the issue related to the Fleet Provisioning key file, we have created a hotfix to address the Segmentation fault that you're seeing. The PR can be found here: https://github.com/awslabs/aws-iot-device-client/pull/102 . If you pull the latest version of the `main` branch, the segmentation fault should be replaced with a clean `ABORT` of the Device Client since the client cannot be properly constructed. 

Thanks again for providing your logs and build setup information!

**Comment by HarshGandhi-AWS** [comment]
Hello @janborch . Thank you for reaching out to us with this issue. We have made some changes in our code base to provide support for taking device specific private key through CLI and JSON config file which will be used further by the Device Client to create a secure MQTT connection with IoT core after fleet provisioning using CSR file is completed. The PR for this change can be found here: #104 . 

Thanks again and let us know if it resolves the issue you were facing earlier.

**Comment by janborch** [comment]
Applied PR #104 and confirm that I can use the FP feature by providing a CSR and a private key using the `device-key` JSON entry. 
[aws-iot-device-client.log](https://github.com/awslabs/aws-iot-device-client/files/5953666/aws-iot-device-client.log). 

But got a core dump when interrupting the client using CTRL-C on the shell with the following error:
```
^Cterminate called after throwing an instance of 'std::future_error'
  what():  std::future_error: Future already retrieved
Aborted (core dumped)
```
[core-aws-iot-device-.97065.ip-192-168-11-161.1612896817.zip](https://github.com/awslabs/aws-iot-device-client/files/5953677/core-aws-iot-device-.97065.ip-192-168-11-161.1612896817.zip)

**Comment by HarshGandhi-AWS** [comment]
@janborch Thank you for confirming PR #104 resolves the issue you were facing earlier. 
Regarding core dump issue, at which point did you hit CTRL-C on the shell to abort the program? Was it while running Fleet Provisioning feature or any other Device client feature?

**Comment by janborch** [comment]
I ran the device client to test the FP feature, after the successful key provisioning I exited the running client using CTRL-C. Refer to attached logs

**Comment by matthewpaul** [comment]
Thanks @janborch. Sounds like we should file a new issue to address stability challenges when receiving interrupt signals, but we can probably close this issue out.

**Comment by matthewpaul** [comment]
@janborch new issue filed here: https://github.com/awslabs/aws-iot-device-client/issues/110
