### ISSUE TITLE
Add support to pass 'Device Configuration' data down to the device when using AWS IoT Fleet Provisioning

### ISSUE THREAD

**Issue by janborch** [awslabs/aws-iot-device-client#103]
The AWS IoT Fleet provisioning feature allows arbitrary data to be passed down to the device after the cloud-side provisioning as explained here: https://docs.aws.amazon.com/iot/latest/developerguide/provision-template.html#device-config

AWS IoT Device client currently does not make this data accessible to the device. 

An option is to append the 'Device Configuration'  data to the `runtime-config` file to allow other software running on the device to read the data.

```
{
"runtime-config": {
    "completed-fp": true,
    "cert": "/root/.aws-iot-device-client/keys/xxxxxxxxxxxxxxx-certificate.pem.crt",
    "key": "/home/ubuntu/device.key",
    "thing-name": "ThingName01",
    "device-configuration":{
             "Foo": "Bar",
             "customer-id": "1234556"
    }
    }
}

```

**Comment by HarshGandhi-AWS** [comment]
Hello @janborch ,
 
Thank you for suggesting us this enhancement in Fleet Provisioning feature. As requested we have [made changes](https://github.com/awslabs/aws-iot-device-client/pull/141) in the code-base for providing support for storing Fleet Provisioning configurations passed via Fleet Provisioning template in the runtime-config file. 
I am closing this issue now, please feel free to reopen this issue or create a new one if required. 

Thank you,
Harsh Gandhi
