### ISSUE TITLE
Address stability issues when receiving signal interrupts

### ISSUE THREAD

**Issue by matthewpaul** [awslabs/aws-iot-device-client#110]
Currently, we have some stability issues when receiving signal interrupts (such as CTRL-C on the command line) that may cause a core dump from the Device Client (as reported by @janborch). We need to review our handling of these interrupts and provide stability improvements to the code base.

**Comment by HarshGandhi-AWS** [comment]
This issue is been resolved now. Please feel free to reopen this issue or create a new one if you see any segmentation faults. 
PR: https://github.com/awslabs/aws-iot-device-client/pull/281
