### ISSUE TITLE
systemd script does not have enough info to run

### ISSUE THREAD

**Issue by rpcme** [awslabs/aws-iot-device-client#173]
**Describe the bug**

The systemd script runs /sbin/aws-iot-device-client with no options.

No one would ever install configuration, certificate, key, and so
forth to home directory, which is the default, under this condition.

The script should have --config-file flag with the default system
volatile install location which is /etc. Please define the expected
location for this file in documentation, and then configure the proper
system config file in the systemd script.

**To Reproduce**

look at the systemd script here

https://github.com/awslabs/aws-iot-device-client/blob/main/setup/aws-iot-device-client.service

**Expected behavior**

systemd script should invoke aws-iot-device-client with --config-file
or have sane system level defaults for key configuration and secure
data.

**Actual behavior**

Please see bug section

**Logs**

Not applicable

**Environment (please complete the following information):**
 - OS: all
 - Version: 1.4.0
 - Architecture: x86-64, AARCH64, RISC-V
 - Device Client commit: tag v1.4.0

**Additional context**

none

**Comment by satheshantanu** [comment]
Hi @rpcme thanks for this - we are working to build the solution to this issue.
