### ISSUE TITLE
Consider --config-dir to read in multiple configuration files

### ISSUE THREAD

**Issue by rpcme** [awslabs/aws-iot-device-client#174]
**Is your feature request related to a problem? Please describe.**

aws-iot-device-client has the flag --config-file which allows a single
monolithic configuration file.

It is possible that an installation could have any number of features,
making some of the json structures in the template irrelevant or even
trigger unnecessary behavior.

**Describe the solution you'd like**

Instead of pointing to a single file, point to a directory and read
any number of individual configuration files that contribute to the
overall configuration. This behavior is consistent with most
UNIX, Linux, and UNIX-like derivative systems.

**Describe alternatives you've considered**

JSON parsing at installation time.  It hurts.

**Additional context**

Please contact internal AWS if more information needed.

**Comment by satheshantanu** [comment]
HI @rpcme, thank you for your inputs. We believe that providing a "config-dir" option will create potential ambiguity when accepting multiple config files as input. For example, do overlapping entries overwrite or append? do we establish order of the config files?

Instead, we currently offer a way for customers to be more specific, by using 
`./aws-iot-device-client --config-file you/config-file/path`
See our demo documentation for more details: 
./aws-iot-device-client --config-file ~/dc-configs/dc-pubsub-config.json

Please let us know if you have any more questions, or if you have a specific use case that requires the customer to point to a config directory. We will be deprioritizing this issue for now.
