### ISSUE TITLE
Builds fail against uclibc and musl

### ISSUE THREAD

**Issue by aduskett** [awslabs/aws-iot-device-client#186]
Two issues:
1) Building against uclibc results in the error:
`error: 'va_list' has not been declared`

2) Building against musl results in the error:
`error: 'mode_t' has not been declared`

**To Reproduce**

1. `git clone git@github.com:aduskett/buildroot-aws-iot.git`
2. `cd buildroot-aws-iot`
2. `rm aws/package/aws-iot-device-client/000{2,3}*` 
3. `docker-compose build`
4. uclibc failures: `VERBOSE="true" TARGET="test_uclibc" BUILD_PACKAGE="aws-iot-device-client" docker-compose up` 
5. musl failures: `VERBOSE="true" TARGET="test_musl" BUILD_PACKAGE="aws-iot-device-client" docker-compose up`

**Expected behavior**

aws-iot-device-client should build against uclibc and musl without failures.

**Actual behavior**

The build fails to compile without the above patches that are removed in step 2.

**Environment (please complete the following information):**
 - HOST OS: Ubuntu 21.10
 - Build OS: Ubuntu 20.04 (Docker)
 - Target OS: Buildroot 2021.08.1 
 - Version: 1.4
 - Architecture: x86-64 (Although the same failure would happen with any architecture.)

**Additional context**
The reason for the issue report is because I am not sure the patches I made are the correct solution to the problem. They do fix the build failures, but I am not comfortable submitting the patches in a pull request. In addition, there is also a third patch that adds an option to skip building tests. Please let me know if you are interested in that as well.

Thanks!

Adam

**Comment by HarshGandhi-AWS** [comment]
Hello @aduskett , thank you for reaching out to us with this issue. I have tried reproducing the issue multiple times but I am not able to do so. I have tried running it on my Mac (OS: Big Sur 11.6.2) and also on an ec2 instance running Ubuntu (OS: 18.04) but had no luck reproducing the issue. I did not see any build failure. I will try building Device Client on an ec2 instance running Ubuntu 20.04 just to be sure. 

Meanwhile, can you double check if you are still seeing any build issue? 

Regards, 
Harsh Gandhi

**Comment by aduskett** [comment]
Hello @HarshGandhi-AWS .

Yes, by following the above steps I was able to reproduce the build failure. Did you copy and paste the commands above?

Regards,
Adam

**Comment by HarshGandhi-AWS** [comment]
Hello @aduskett , 

Current version of Device Client does not support musl library. We will let you know through once the Device Client provide support for it in future.

Regards, 
Harsh Gandhi

**Comment by williamlai** [comment]
@aduskett I believe I experience the same issue as you, and I've fixed it by including header file `sys/stat.h` in `source/util/FileUitls.h` for `mode_t`. I've verified it on an OpenWRT device which uses Musl-C as its C runtime library.
