### ISSUE TITLE
Cannot work alongside GreenGrass V1 !

### ISSUE THREAD

**Issue by nbcs-temp** [awslabs/aws-iot-device-client#189]
**Describe the bug**

Cannot establish stable MQTT sessions on devices already running GG.service.

**To Reproduce**

1. Setup a new device with GreenGrass V1.
2. Deploy aws-iot-device-client reusing the same "certs" already deployed and used by GG under /greengrass/certs.
3. Manual launch of aws-iot-device-client shows continous reconnects to MQTT IoT Core. (Keeps being rejected)
4. Secure Tunneling was the main tested feature. Everything works once greengrass deamon is stopped/disabled.

**Expected behavior**

We would need to have SSH sessions to control devices running GreenGrass V1.

**Actual behavior**

See above.

**Logs**
N/A

**Environment (please complete the following information):**
 - OS: Debian or RPI,...
 - Version : Any versions
 - Architecture: ARM
 - Device Client commit: ??

**Additional context**

**Comment by HarshGandhi-AWS** [comment]
Hello @nbcs-temp , we would recommend you using Device Client as a component on Greengrass devices. We do not provide support for running Device Client as a component on Greengrass V1. Greengrass V2 and Device Client provides a pre-made component for using Secure tunneling feature. https://docs.aws.amazon.com/greengrass/v2/developerguide/secure-tunneling-component.html

Is this something that you've seen and looked into before?

Regards, 
Harsh Gandhi

**Comment by HarshGandhi-AWS** [comment]
Hello @nbcs-temp  , I am closing this ticket now since we haven't heard back from you. Please review my previous comment and feel free to reopen this issue or create a new one if still have any questions regarding the Device Client and we will be more than happy to help you.

Regards,
Harsh Gandhi
