### ISSUE TITLE
Feature request: PubSub to be able to connect to a localhost on certain port(tcpclient), read data and publish to certain topic on aws iot core. 

### ISSUE THREAD

**Issue by 10zintsering** [awslabs/aws-iot-device-client#194]
In our project, we want to use aws-iot-device-client-cpp-v2 on Raspberrypi 3B+ running Buster/Stretch/Wheezy. 

Current pubsub feature is able to read from a file and publish it to a configured topic to aws iot core. It can also send default Hello World payload to iot core at the beginning and also when device receives publish triggering subscribe message(DC-Publish).

What we would like to have is: 

We can also configure an ip address and a port number on a .aws-iot-device-client.conf configuration page.

When Pubsub feature is enabled, the feature will create a socket and makes a tcp connection to the configured ip and port.

Function similar to PublishFileData(), which will publish data received from the tcp connection is publish to a configured topic, is trigered everytime a data is received from the tcp connection. 

Iot Jobs and other services should also be able to function where an event is received. Ideally, these services can be handled alongside the pubsub is publishing data, but it's also fine if pubsub stops publishing data while the other event is handled and resumes back to publishing data once it's completed.

**Comment by ilevyor** [comment]
Take a look at the pub-sub samples found here:
https://github.com/aws/aws-iot-device-sdk-cpp-v2/tree/main/samples
https://github.com/aws/aws-iot-device-sdk-python-v2/tree/main/samples

**Comment by HarshGandhi-AWS** [comment]
Hello @10zintsering , thank you for reaching out to us; we value all feedback we are getting over here. What you are asking is a major change in the implementation of the Pub-Sub feature sample. Please be patient with us until I discuss this feature request with our team and come-up with a better solution. 

Regards, 
Harsh Gandhi

**Comment by 10zintsering** [comment]
Thank you Harsh for your help. I will be patiently waiting for your solution.

**Comment by HarshGandhi-AWS** [comment]
Hello @10zintsering @ilevyor , we took your request to work on this enhancement and created a new feature in Device Client to transmit sensor data over MQTT using the client. Please have a look at this new feature and let us know if you wish us to make any more developments in the feature or in the Device Client in general. 

Ref: [Sensor Publish feature](https://github.com/awslabs/aws-iot-device-client/blob/main/source/sensor-publish/README.md) 

Thank you,
Harsh Gandhi
