### ISSUE TITLE
Client Job is received but nothing is being executed

### ISSUE THREAD

**Issue by JoseOrtega17** [awslabs/aws-iot-device-client#231]
Hi. 

The problem is with the example: download-file.sh, the output file should be in the "/tmp/"  folder.
When I place the job, the device receives it but there is not any file downloaded.

Using the example from : https://github.com/aws/aws-iot-device-sdk-python-v2/blob/main/samples/jobs.py

python3 jobs.py --endpoint abc1235667-ats.iot.us-east-1.amazonaws.com --cert /home/jetsonclient/certs/certificate.pem.crt --key /home/jetsonclient/certs/private.pem.key --thing-name jetsonclient --verbosity Info

**Expected behavior**

Should download a file and paste it in /tmp/

**Actual behavior**

Executes the job but nothing is downloaded

**Logs**
Output:
Trying to start the next job...
Publishing request to start next job...
Published request to start the next job.
Request to start next job was accepted. job_id:download_test job_document:{'version': '1.0', 'steps': [{'action': {'name': 'Download-File', 'type': 'runHandler', 'input': {'handler': 'download-file.sh', 'args': ['https://github.com/awslabs/aws-iot-device-client/archive/refs/tags/v1.3.tar.gz', '/tmp/'], 'path': '"/tmp/'}, 'runAsUser': 'jetsonclient'}}]}
Starting local work on job...
Done working on job.
Publishing request to update job status to SUCCEEDED...
Published request to update job.
Request to update job was accepted.
Received Next Job Execution Changed event: None. Waiting for further jobs...

**Environment (please complete the following information):**
 - OS: [Ubuntu 18.06]
 - Architecture: [ARM64]
- Jetson nano 

**Additional context**

Is there an option to increase the logs?

**Comment by xlcheng1** [comment]
Hi @JoseOrtega17 

Thank you for reaching out!

We are aware of this issue and have already assigned one of our engineers working on it. The update should be pushed soon. Meanwhile, one possible workaround you could try is to pass the path including the file name, like /tmp/downloaded_file.tar.gz , instead of /tmp/ 

Let me know if you have any other questions!

**Comment by HarshGandhi-AWS** [comment]
Hi @JoseOrtega17 , quick question: Are you using [Device Client](https://github.com/awslabs/aws-iot-device-client/) or the [python sample](https://github.com/aws/aws-iot-device-sdk-python-v2) you shared to run the IoT Jobs feature? From the logs, it looks like you are using the Python sample. If you are using the python sample, I would suggest you to create an issue in that repo.

**Comment by JoseOrtega17** [comment]
Hi @HarshGandhi-AWS I'm using the python sample and the download-file.sh sample, I though they were compatible so Ill create the ticket in that repo.  I also tried the path including like /tmp/downloaded_file.tar.gz. Thanks for your information!
