### ISSUE TITLE
What was the fix for cmake-toolchain/Toolchain-aarch64.cmake libcrypto for ?

### ISSUE THREAD

**Issue by BestITUserEUW** [awslabs/aws-iot-device-client#232]
Hey,
this is not a bug but a small question. I would like to know what this fix was for:

> #Fix some wonkiness in the S2N build
SET(LibCrypto_SHARED_LIBRARY /usr/lib/aarch64-linux-gnu/lib/libcrypto.so)
SET(LibCrypto_STATIC_LIBRARY /usr/lib/aarch64-linux-gnu/lib/libcrypto.a)
because i'm encountering an error after compilation in aws-iot-sdk-cpp-v2 with arm64-musl toolchain:

> Fatal error condition occurred in /pathTo/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2/src/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-cal/source/unix/openssl_platform_init.c:488: process && "Unable to load symbols from process space"
Exiting Application
No call stack information available
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted (core dumped)

**Comment by xlcheng1** [comment]
Hi @BestITUserEUW 

Thank you for reaching out!

Unfortunately, we do not support musl at the moment.

Calvin

**Comment by BestITUserEUW** [comment]
Ok thank you for the fast Answer
