### ISSUE TITLE
AWS IoT Core MQTT message -> Timestream with multi-dimension support

### ISSUE THREAD

**Issue by reghardtp** [awslabs/aws-iot-device-client#270]
Hi,
We are looking to use IoT Core with AWS iot device client to send MQTT messages that have multi-dimension measures. ie. 10 channels of ADC information for the same timestamp being recorded at the same time.

Currently, IoT core -> Timestream action integration doesn't support multi-dimensions (unless I just can't find it :-D)

One work around is to use Lambda to unpack an array of values into a multi-dimension recordwrite to timestream. Seems like the only workaround, but should probably be natively supported.

Thanks for the consideration

Cheers
Regh

**Comment by HarshGandhi-AWS** [comment]
Hey @reghardtp , does the above link helps you? Do you still think there is work involved to provide support to send MQTT messages that have multi-dimension?

Please let us know what you think so we can help you resolve this issue as soon as possible.

Regards,
Harsh Gandhi

**Comment by reghardtp** [comment]
Hi HarshGandhi, thanks for the follow up.

I have managed to use a lambda to unpack the data and keep going.
Thanks!
