### ISSUE TITLE
The aws-iot-device-client.service file uses a hardcoded parameter

### ISSUE THREAD

**Issue by asadpiz** [awslabs/aws-iot-device-client#283]
**Describe the bug**

The sytemd service unit configuration file has a hardcoded parameter https://github.com/awslabs/aws-iot-device-client/blob/fc64b02034759af2a14362b282592890e2c1314c/setup/aws-iot-device-client.service#L7

Due to this check in the setup.sh https://github.com/awslabs/aws-iot-device-client/blob/fc64b02034759af2a14362b282592890e2c1314c/setup.sh#L19

If anyone runs the setup script with a user other than root or place the aws-iot-device-client.conf  file anywhere other than /etc the script will fail with the following error:

`[ERROR] {Config.cpp}: *** AWS IOT DEVICE CLIENT FATAL ERROR: Config file specified in the CLI doesn't exist: '/etc/.aws-iot-device-client/aws-iot-device-client.conf' ***`

**To Reproduce**

1. Execute setup.sh without root or as any other user.
2. See error

`[ERROR] {Config.cpp}: *** AWS IOT DEVICE CLIENT FATAL ERROR: Config file specified in the CLI doesn't exist: '/etc/.aws-iot-device-client/aws-iot-device-client.conf' ***`

**Expected behavior**

The service should run without the above error.

**Actual behavior**

The service fails to start with the above mentioned error.

**Logs**

If applicable, add full logs of errors and outputs to help explain your problem. Preferably, you can also [increase the verbosity of the logs](https://github.com/awslabs/aws-iot-device-client#logging).

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version N/A
 - Architecture: x86-64
 - Device Client commit: latest

**Additional context**

Issue arises due to the following changes:
https://github.com/awslabs/aws-iot-device-client/pull/259
which was to fix the following issue:
https://github.com/awslabs/aws-iot-device-client/issues/173

**Comment by asadpiz** [comment]
Here's what I put together: https://github.com/awslabs/aws-iot-device-client/pull/284

1. This works for new users who are able to use the root user.
2. Works for new users who have other custom sudo users.
3. The script won't fail if the else condition is executed:
https://github.com/awslabs/aws-iot-device-client/blob/fc64b02034759af2a14362b282592890e2c1314c/setup.sh#L22

I believe the suggestion of the bug comes from the fact that L22 is always going to fail if the config path is hardcoded in the service.

**Comment by RogerZhongAWS** [comment]
Thanks Asad, I think your suggestion makes sense. I'll try to get this approved.

**Comment by RogerZhongAWS** [comment]
merged PR
