### ISSUE TITLE
REGEX error in CMakeLists.txt.versioning when building using buildroot

### ISSUE THREAD

**Issue by stwirth** [awslabs/aws-iot-device-client#297]
**Describe the bug**
I'm trying to build this repository using buildroot with a mips-based toolchain.
The version extraction using git fails with
```
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Using Git to calculate AWS IoT Device Client version information...
fatal: No names found, cannot describe anything.
CMake Error at CMakeLists.txt.versioning:41 (string):
  string sub-command REGEX, mode MATCHALL needs at least 5 arguments total to
  command.
```

**To Reproduce**

Can't disclose my setup but probably reproducible with a standard buildroot, adding this repo as a github package:
```
# aws-iot-device-client.mk 
################################################################################
#
# aws-iot-device-client
#
################################################################################

AWS_IOT_DEVICE_CLIENT_VERSION = v1.7
AWS_IOT_DEVICE_CLIENT_SITE = $(call github,awslabs,aws-iot-device-client,$(AWS_IOT_DEVICE_CLIENT_VERSION))

$(eval $(cmake-package))
```

**Expected behavior**
Build runs through.

**Actual behavior**

cmake fails

**Logs**
```
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /project/out/product/myboard/obj/buildroot-intermediate/host/bin/mips-linux-gnu-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /project/out/product/myboard/obj/buildroot-intermediate/host/bin/mips-linux-gnu-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Using Git to calculate AWS IoT Device Client version information...
fatal: No names found, cannot describe anything.
CMake Error at CMakeLists.txt.versioning:41 (string):
  string sub-command REGEX, mode MATCHALL needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:152 (include)


-- Generated AWS IoT Device Client version: vNOTFOUND.NOTFOUND.0-6d7e21bd0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /project/out/product/myboard/obj/buildroot-intermediate/host/mipsel-buildroot-linux-gnu/sysroot/usr/lib/libcrypto.a (found version "1.1.1g")  
-- Configuring done
-- Generating done
```
**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04
 - Architecture: x86-64, cross-compiling for MIPS
 - Device Client commit: tag v1.7

**Additional context**

**Comment by stwirth** [comment]
This is probably caused by buildroot stripping away the `.git` folder before building.

**Comment by stwirth** [comment]
I think the solution to this would be to trigger the `else()` clause in `CMakeLists.txt.versioning` when `execute_process(COMMAND ${GIT_EXECUTABLE} describe...` fails.

**Comment by RogerZhongAWS** [comment]
Hello, thanks for reaching out and describing your issue. We will try to reproduce the issue and investigate why the version information is not being extracted properly. Please stay in touch for further updates.

Regards,
Roger

**Comment by stwirth** [comment]
Hi @RogerZhongAWS, I'm pretty sure it's caused by buildroot removing the `.git` repository after downloading (to handle it like a source tarball). This `git describe` call then fails:
https://github.com/awslabs/aws-iot-device-client/blob/745e6a85588b8f1d0768e77a6798254b0872fbd6/CMakeLists.txt.versioning#L23
which makes the subsequent REGEX fail.
The return code of `execute_process` should be checked before using it's output.

**Comment by RogerZhongAWS** [comment]
Thanks for the suggestion @stwirth 
I created a PR that checks the return code as you described: #298
Please check it out and see if it is working for you. Basically, if we can not find git or if that command fails, we fall through and call load_version_from_file() instead.

**Comment by RogerZhongAWS** [comment]
Hello, @stwirth. Just following up, were you able to checkout and test commit 885052606738eb5123a5967705dc8d9206d570ae from PR #298 using your buildroot configuration?
