### ISSUE TITLE
Failed to stop aws-iot-device-client.service: Unit aws-iot-device-client.service not loaded.

### ISSUE THREAD

**Issue by ddmakadia1699** [awslabs/aws-iot-device-client#315]
Getting an error while installing AWS IoT Device Client as a service

https://catalog.us-east-1.prod.workshops.aws/workshops/6d30487a-48e1-4631-b6bc-5602582800b5/en-US/chapter3-deviceclientsetup/30-dc-setup (3.3 Quick-configure AWS IoT Device Client - step-12)

Do you want to install AWS IoT Device Client as a service? y/n
y
Installing AWS IoT Device Client...
/bin/systemctl
Failed to stop aws-iot-device-client.service: Unit aws-iot-device-client.service not loaded.
Created symlink /etc/systemd/system/multi-user.target.wants/aws-iot-device-client.service → /etc/systemd/system/aws-iot-device-client.service.
● aws-iot-device-client.service - AWS IoT Device Client
   Loaded: loaded (/etc/systemd/system/aws-iot-device-client.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2022-08-16 12:15:42 UTC; 8ms ago
  Process: 8852 ExecStart=/sbin/aws-iot-device-client --config-file $CONF_PATH (code=exited, status=1/FAILURE)
 Main PID: 8852 (code=exited, status=1/FAILURE)

Aug 16 12:15:42 ip-192-168-128-6 systemd[1]: Started AWS IoT Device Client.
Aug 16 12:15:42 ip-192-168-128-6 aws-iot-device-client[8852]: 2022-08-16T12:15:42.511Z [ERROR] {Config.cpp}: *** AWS IOT DEVICE CLIENT FATAL ERROR: Config file specified in the 
Aug 16 12:15:42 ip-192-168-128-6 systemd[1]: aws-iot-device-client.service: Main process exited, code=exited, status=1/FAILURE
Aug 16 12:15:42 ip-192-168-128-6 systemd[1]: aws-iot-device-client.service: Failed with result 'exit-code'.
...skipping...
● aws-iot-device-client.service - AWS IoT Device Client
   Loaded: loaded (/etc/systemd/system/aws-iot-device-client.service; enabled; vendor preset: enabled)
error: could not lock config file /home/ubuntu/.gitconfig: File exists
ubuntu:~ $

**Comment by HarshGandhi-AWS** [comment]
Hey @ddmakadia1699 , can you also share the device client logs with us. Without complete logs, we cannot debug the issue. 
You can find the logs in this log file: `/var/log/aws-iot-device-client/aws-iot-device-client.log`

**Comment by ddmakadia1699** [comment]
Hi @HarshGandhi-AWS, 
not sure where to find logs. Can you guide me with that?
Do I need to check "show hidden files"? 

Below is the current file system in cloud9.

<img width="215" alt="image" src="https://user-images.githubusercontent.com/38184843/184951105-16947ab9-6be5-4a13-9e42-60a5ea93bb6b.png">

**Comment by HarshGandhi-AWS** [comment]
Can you run this command and see if you are able to find any logs? 

```
cat /var/log/aws-iot-device-client/aws-iot-device-client.log
```

**Comment by ddmakadia1699** [comment]
I think it is not created yet.

<img width="388" alt="image" src="https://user-images.githubusercontent.com/38184843/184953992-4e016397-044b-48e3-b921-3de63a765288.png">

**Comment by HarshGandhi-AWS** [comment]
Okay. Let me try to reproduce the issue by following the workshop steps.

**Comment by HarshGandhi-AWS** [comment]
Hey @ddmakadia1699 , I was able to reproduce the issue. It is failing because client is not able to find the config file at this location: `/etc/.aws-iot-device-client/aws-iot-device-client.conf`. 
To resolve this issue, can you [update this line ](https://github.com/awslabs/aws-iot-device-client/blob/main/setup/aws-iot-device-client.service#L7) with correct config file path and try running `sudo ./quick-setup.sh` step again? The correct file name for you will be `/root/.aws-iot-device-client/aws-iot-device-client.conf`. 

I will take an action item for updating the workshop documentation to avoid confusion in future.

**Comment by ddmakadia1699** [comment]
Thanks for the quick resolution.
