### ISSUE TITLE
OpenSSL compatibility

### ISSUE THREAD

**Issue by DarwinCAV** [awslabs/aws-iot-device-client#347]
During the build phase of this project on Ubuntu 22.04 LTS with fully configured openssl 3.0.2, error occurs saying that OpenSSL cannot be found.

The project dependencies state that minimum requirements are OpenSSL 1.1.1.1 and it sounds like that it is not compatible with later versions.

Also, note that on the Ubuntu machine "openssl" command is with all lowercase letters and in CMakeLists.txt "OpenSSL" is typed with capital letters.

**To Reproduce**

Steps to reproduce the behaviour:
1. Install Ubuntu 22.04 LTS
2. Download this git project.
3. Open README.md and follow Installation Instructions  
4. when run build .\.. see the following error: CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindOpenSSL.cmake:574 (find_package_handle_standard_args)
  CMakeLists.txt:160 (find_package)
5. From terminal type 'openssl version -a' and observe that openssl is installed: openssl version -a
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
built on: Mon Jul  4 11:20:23 2022 UTC
platform: debian-amd64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -ffile-prefix-map=/build/openssl-Q8dQt3/openssl-3.0.2=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-3"
MODULESDIR: "/usr/lib/x86_64-linux-gnu/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0xfffa32035f8bffff:0x184007a4219c27ab

**Expected behavior**

Expected behaviour is that "CMake" finds openssl and builds the project.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04 LTS
 - Architecture: x86-64

**Comment by RogerZhongAWS** [comment]
Hello, thanks for reaching out. This error message usually shows up when you do not have the openssl development library with c header files. You can install it through `apt install libssl-dev`. Please try that if you have not already.
