### ISSUE TITLE
Question: How certificate rotation works with fleet provisioning feature using aws iot device client?

### ISSUE THREAD

**Issue by Kammula280** [awslabs/aws-iot-device-client#365]
**Description:** I am using aws-iot-device-client for a couple devices with fleet provisioning feature. When using fleet provisioning, a runtime configuration is created when thing is successfully registered in AWS IOT Core like below.
```"runtime-config": {
    "completed-fp": true,
    "cert": "/path/to/newly/created/certificate.pem.crt",
    "key": "/path/to/private.pem.key",
    "thing-name": "NewlyProvisionedThingName"
    }
}
```

If I would like to rotate certificates(x.509, private key), I am either deleting the above configuration file or changing the "completed-fp" parameter to false. Per documentation when the "completed-fp" is false, aws-iot-device-client will re-provision the device which in turn generates a new set of certificates for the device. But the **problem** is  old certificates will still live on the device and are not removed from AWS IOT Core. 

**Question:** While using aws-iot-device-client with fleet provisioning feature, Could you please provide me the best way on how to rotate certificates and automate the process. Also, Is re-provisioning the device will cause any issues and is it fine to do it?

**Initial thoughts:** My initial thought is to create a lambda function and follow below steps
1. Create AWS IOT Job to change/remove runtime configuration file and restart aws-iot-device-client service.
2. Create AWS IOT Job to delete the old certificates by taking certificate name and location as input parameter on the device.
3. Lambda function to receive input on which devices to rotate certificates and run below jobs.
4. Run the above created job on the each device specified which will generate a new set of certificates by reprovisioning the device.
5. Once job is successful, Query for the list of certificates and remove everything based on date created except the new one and run another job to delete the old certificates
6. Finally remove the certificates on the IOT Core based on date created.

This process looks a bit sketchy, so wanted to know what will be best way to rotate certificates.

Thank you!

**Comment by shangabl** [comment]
Hi @Kammula280,

Thank you for reaching out. Automated certificate rotation is something we want to support in the future, but we don't currently have a timeline!

I think your idea outlined above would work.

However, re-provisioning the device will result it in provisioning a whole new IoT Thing. So, it is more like starting over than rotating the certificate.

The way to actually rotate the certificates is outlined here: https://aws.amazon.com/blogs/iot/how-to-manage-iot-device-certificate-rotation-using-aws-iot/

This would require some development on the Device Client side however. This is on my radar now but unfortunately I can't make any guarantees as to when it might be available.

You can of course attempt to do a custom implementation of this building on top of the Device Client and are welcome to ask any questions here and the team will answer.

On the cloud side you would need to setup Device Defender, SNS, and Lambda like it outlines in the above link.

On the Device Side:

1. Need to subscribe to ```management/topic/{clientId}/csr_req``` and add code for generating a Certificate Signing Request and publishing it to ```management/topic/{clientId}/csr_res```

2. Need to subscribe to ```management/topic/{clientId}/crt``` and add code for attempting to re-establish MQTT connection when new certificate is received on that topic. If successful, update config to point to new certificate, delete old certificate, publish to ```management/topic/{clientId}/crt_ack```. If not successful, publish to ```management/topic/{clientId}/crt_err``` with error.

You could try doing this with the Pub/Sub sample feature gives examples of how to Pub/Sub to topics.

Hope that helps!

**Comment by Kammula280** [comment]
Hi @shangabl 
Thank you for your quick response and I really appreciate your effort on iot-device-client. Glad now that you have certificate rotation on your radar now. I am not familiar with cpp to perform the Device Side changes. I have implemented the below approach for device certificate rotation and will put some notes here if it helps anyone. 

During the implementation, I found a couple issues. If you believe they are bugs and need a separate issue, let me know I will open separate issues.

**Issue1:**
While using fleet provisioning feature, Once the thing is registered a runtime config file is generated(~/.aws-iot-device-client/aws-iot-device-client-runtime.conf). This file consists of an additional character in the end which causes issues while parsing json.

Example file with additional charcter in the last line
```
{
"runtime-config": {
    "completed-fp": true,
    "cert": "/root/.aws-iot-device-client/keys/61ab473dd81f24753c5d866d7babe1f4b47dd293d3232-certificate.pem.crt",
    "key": "/root/.aws-iot-device-client/keys/fbrhvnd866d7babe1f4b47dd293d3232-private.pem.key",
    "thing-name": "final_final13",
    "device-config": {

        }
    }
}**^@**
```

**Issue2:**
While trying to rotate certificates in the device, I am getting new certificates calling AWS API and changing the runtime configuration file by replacing the  "cert" and "key" with new certificate path.

**Goal** Here is to reload the aws-iot-device-client with new configuration file.

To achieve reloading of aws-iot-device-client with new configuration file, I am trying to restart the aws-iot-device-client using jobs feature. Issue here is when try to run the job to restart the aws-iot-device-client, the job never completes and the aws-iot-device-client restart is ending in an infinite loop. 

Approach I tried to restart aws-iot-device-client using jobs feature is
1. Create another main process/subprocess within the job handler and finish the job process but the job process is not quitting till main process/subprocess are finished.
2. From job handler, create a shell script file and set permissions. Execute the shell script as sub process or another main process
```
#!/usr/bin/env sh
set -e
sleep 30
sudo systemctl restart aws-iot-device-client
```
3. The job is never completed and ends up in infinite loop.

**Question** How can achieve the reload the aws-iot-device-client with new configuration file? Also, Do you think there will be a need for the restart of aws-iot-device-client from jobs feature if the user wants to? I am not sure if there is any heart beat check and aws-iot-device-client can restart itself if connection to aws fails.

I can provide some log files and any other information needed if this is not expected behavior.

**Implementation of Device certificate rotation notes**
1. On Cloud side, setup Device defender and SNS alerts of Device certificate expiration check to be sent to Lambda function.
    Some prerequisites will be setting up iot role alias so device can get aws credentials to call apis. 
2. Lambda function to execute a job on the device.
3. Job document
```
{
  "version": "1.0",
  "steps": [
    {
      "action": {
        "name": "test",
        "type": "runHandler",
        "input": {
          "handler": "rotatecert.py",
          "args": [
            " policy name",
            "Credentials provider url",
            "region"
          ],
          "path": "/etc/.aws-iot-device-client/jobs/"
        },
        "runAsUser": "ubuntu"
      }
    }
  ]
}
```

4. Job Handler, Does the following
a. Read the runtime configuration file
b. Get AWS credentials using iot credentials endpoint
c. Generate new certificates
d. Save the certificate files and set permissions
e. replace the runtime configuration file with new certificate paths.
f. Reload the aws-iot-device-client to pickup new configuration (**Not able to achieve this**)
g. Revoke the old certificates


```
#!/usr/bin/env python3
import sys
import boto3
import urllib3
import json
import subprocess
import os

policy_to_attach=sys.argv[2]
credentials_url = sys.argv[3]
region = sys.argv[4]

try:
    device_iot_config_file = open('/root/.aws-iot-device-client/aws-iot-device-client-runtime.conf')
    device_iot_config_data = json.load(device_iot_config_file)
    device_iot_config_file.close()
except:
    device_iot_config_file = open('/root/.aws-iot-device-client/aws-iot-device-client-runtime.conf')
    data = device_iot_config_file.read()
    new=data[:-1]
    device_iot_config_data= json.loads(new)
    device_iot_config_file.close()

cert_file =device_iot_config_data["runtime-config"]["cert"]
key_file = device_iot_config_data["runtime-config"]["key"]
thing_name = device_iot_config_data["runtime-config"]["thing-name"]
keys_folder='/root/.aws-iot-device-client/keys/'
iot_client_restart_script_folder='/etc/.aws-iot-device-client/jobs/'

retries = urllib3.Retry(connect=5, read=2, redirect=5)
http = urllib3.PoolManager(
    cert_file=cert_file,
    key_file=key_file,
    cert_reqs="CERT_REQUIRED",
    headers={
        'x-amzn-iot-thingname': thing_name
    },
    retries=retries
)

def get_boto_session():
    print(credentials_url)
    resp = http.request("GET", credentials_url)
    print(resp.status)
    if resp.status != 200:
        raise Exception("Failed to retrieve STS token: {}".format(resp.reason))
    creds = json.loads(resp.data)['credentials']
    return boto3.session.Session(aws_access_key_id=creds['accessKeyId'], aws_secret_access_key=creds['secretAccessKey'], aws_session_token=creds['sessionToken'], region_name=region)

def list_thing_principals(thingName):
    response = iot.list_thing_principals(
    thingName=thingName
    )
    return response["principals"]

def create_keys_and_certificate(setAsActive):
    response = iot.create_keys_and_certificate(
    setAsActive=setAsActive
    )
    return response

def create_keys_and_certificate_files(filename, content):
    writetofile = open(filename, "w")
    writetofile.write(content)
    writetofile.close()
    return "success"
def create_keys_and_certificate_files_permissions(path, permission):
    os.chmod(path, permission)
    return "success"

def attach_policy(policyName, target):
    response = iot.attach_policy(
        policyName=policyName,
        target=target
    )
    return "success"

def attach_thing_principal(thingName, principal):
    response = iot.attach_thing_principal(
    thingName=thingName,
    principal=principal
    )
    return "success"

def replacetext(filename, old_text,new_text):
    writetofile = open(filename, "r")
    data = writetofile.read()
    data = data.replace(old_text, new_text)
    writetofile.close()

    writetofile = open(filename, "w")
    writetofile.write(data)
    writetofile.close()
    return "success"

#syncronous operation will wait for child process to finish, for asyncronous use Popen
# def restart_service():
#     commands = ["sudo", "systemctl", "restart", "aws-iot-device-client.service"]
#     subprocess.run(commands, shell=False, check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
#     return "success"

def Execute_shell_script(shell_script_path):
    subprocess.Popen(["sh", shell_script_path],shell=False,stdin=None, stdout=None, stderr=None, close_fds=True)
    return "success"

def revoke_certificates(thing_name, new_certificate_certificateArn):

    #get list of certs for this thing
    certsResponse = iot.list_thing_principals(
        thingName = thing_name
    )

    #revoke and delete all certs associated with this thing except for the new one
    for certARN in certsResponse["principals"]:
        if certARN != new_certificate_certificateArn:
            #get cert id
            base,certificateId = certARN.split("/")

            #check its status
            statusResponse = iot.describe_certificate(
                certificateId = certificateId
            )

            if statusResponse["certificateDescription"]["status"] != "REVOKED":
                #revoke the certificate
                updateCertResponse = iot.update_certificate(
                    certificateId = certificateId,
                    newStatus = 'REVOKED'
                )
                print("Revoked cert: " + certificateId)

                #list the policies for the cert so they can be detached
                policiesResponse = iot.list_attached_policies(
                    target=certARN,
                    recursive=False
                )

                #remove the attachement
                for policy in policiesResponse["policies"]:
                    response = iot.detach_principal_policy(
                        policyName=policy["policyName"],
                        principal=certARN
                    )
                    print("Detached policy: " + policy["policyName"])

                #detach the cert from the thing
                response = iot.detach_thing_principal(
                    thingName=thing_name,
                    principal=certARN
                )

                #delete the certificate
                response = iot.delete_certificate(
                    certificateId=certificateId,
                    forceDelete=False
                )
                print("Delete cert: " + certificateId)

    return 'Done'

if __name__ == '__main__':
    sess = get_boto_session()
    iot = sess.client('iot')
    old_certificate_certificateId,base=cert_file.split('/')[-1].split('-')
    #base,old_certificate_certificateId=list_thing_principals(thing_name)[0].split('/')
    new_certificate_details =create_keys_and_certificate(True)
    new_certificate_certificateId= new_certificate_details["certificateId"]
    new_certificate_certificateArn= new_certificate_details["certificateArn"]
    new_certificate_certificatePem =new_certificate_details["certificatePem"]
    new_certificate_PrivateKey=new_certificate_details["keyPair"]["PrivateKey"]
    new_certificate_certificatePem_file=create_keys_and_certificate_files(keys_folder+new_certificate_certificateId+'-certificate.pem.crt', new_certificate_certificatePem)
    new_certificate_PrivateKey_file=create_keys_and_certificate_files(keys_folder+new_certificate_certificateId+'-private.pem.key', new_certificate_PrivateKey)
    new_certificate_certificatePem_file_permission=create_keys_and_certificate_files_permissions(keys_folder+new_certificate_certificateId+'-certificate.pem.crt', 0o644)
    new_certificate_PrivateKey_file_permission=create_keys_and_certificate_files_permissions(keys_folder+new_certificate_certificateId+'-private.pem.key', 0o600)
    attach_policy(policy_to_attach, new_certificate_certificateArn)
    attach_thing_principal(thing_name , new_certificate_certificateArn)
    replacetext("/root/.aws-iot-device-client/aws-iot-device-client-runtime.conf", old_certificate_certificateId,new_certificate_certificateId)
    #restart_service()
    iot_client_restart_script = '#!/usr/bin/env sh\nsleep 30\nset -e\nsudo systemctl restart aws-iot-device-client'
    iot_client_restart_script_file=create_keys_and_certificate_files(iot_client_restart_script_folder+'iot_client_restart_script.sh', iot_client_restart_script)
    iot_client_restart_script_file_permission=create_keys_and_certificate_files_permissions(iot_client_restart_script_folder+'iot_client_restart_script.sh', 0o700)
    #Execute_shell_script(iot_client_restart_script_folder+'iot_client_restart_script.sh')
    revoke_certificates(thing_name, new_certificate_certificateArn)
```

Thank you!

**Comment by shangabl** [comment]
Hi @Kammula280,

Thanks for these notes!

1. I would say this is a bug. The additional character of the runtime configuration file is not something I have seen before. I'll attempt to recreate that issue and see why that is happening. We definitely do not want the runtime configuration file to be invalid JSON. What operating system / architecture are you using? I'll try to recreate using the same.
2. The issue with the infinite loop is due to Device Client restarting during execution of the Job. Device Client Gets Job -> Executes Job via Job handler -> Updates Job. But if it restarts it never updates the Job and then the Job is still pending and it will start over again. We have logic in the reboot.sh handler that deals with this situation. That is a little different because we need to get last boot time, uptime and figure out if we rebooted or not... I think here in your handler you could just use a lock file to track whether or not you have restarted. Check if file exists, if it does not then you restart, if it does exist then don't restart and delete the lock file.

**Comment by Kammula280** [comment]
Hi @shangabl 
For Issue 1, additional character in runtime configuration file, Environment I have used is x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"

Just now, I also tested in below environment and the behavior is same. 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
AMI in AWS =ami-0a6b2839d44d781b2 ( x86_64)

For Issue2, I will try using a lock file an see if I am able to restart the aws-iot-device-client if it is only way to reload with a new runtime configuration file.

Thank you!

**Comment by shangabl** [comment]
I attempted to recreate the issue and I just get valid JSON...

Are you saying it generates the Runtime config with the extra character and then fails to parse the runtime config file and crashes? Can you show error output? Thanks!

**Comment by Kammula280** [comment]
Hi @shangabl 
When I use fleet provisioning feature, a runtime configuration file is created and iot-device-client is running successfully without any errors.

I am only seeing an additional character in the end of the runtime configuration file when use vi editor or when I download the file or when I am programmatically reading that file.

**Comment by RogerZhongAWS** [comment]
Hey @Kammula280 , thanks for posting those screenshots. I see the exact same thing when testing fleet provisioning from my side. "^@" is simply the manifestation of the null terminating character in the file. Small bug that we will push a quick fix for.

**Comment by shangabl** [comment]
Hi @Kammula280,

I also merged a fix for the infinite loop of restarting Device Client service.

I will close this issue out now as we have merged fixes for both the issues you discovered.

Thank you for your help here!

Shane

**Comment by Kammula280** [comment]
Thank you very much Shane!

**Comment by shangabl** [comment]
Hi @Kammula280,

I am re-opening this because I realized we had to revert the fix for the runtime config file fix. We should be merging the fix again shortly but we reverted due to a test failure!

This should be resolved shortly but I wanted to make sure you had the correct information!

Shane
