### ISSUE TITLE
Warning causing error because -Werror, when Jobs enabled

### ISSUE THREAD

**Issue by thomas-roos** [awslabs/aws-iot-device-client#378]
**Describe the bug**

**To Reproduce**

built with Jobs enabled

**Expected behavior**

no warning

**Actual behavior**

Warning causing error because -Werror

**Logs**

[error.log](https://github.com/awslabs/aws-iot-device-client/files/10412482/error.log)

**Environment (please complete the following information):**

 - Architecture: all
 - Device Client commit: bb7ff67e6fc1e307ac55163c82770f411b77462e

**Additional context**
we created a patch to disable error on warnings:
[patch.txt](https://github.com/awslabs/aws-iot-device-client/files/10412520/patch.txt)

**Comment by hrvboy** [comment]
I just saw this issue today. 

Line 198 of JobEngine.cpp should be:
int actionExecutionStatus = 0;

**Comment by rpcme** [comment]
@thomas-roos can you please try fixing this thru patch process to 1/ get this sorted on our end 2/ communicate confirmation here

**Comment by thomas-roos** [comment]
can confirm the patch works - please it merge into mainline
thanks to @hrvboy

**Comment by shangabl** [comment]
Merged. Thanks!
