### ISSUE TITLE
Can we specify a location for setup.sh?

### ISSUE THREAD

**Issue by monelgordillo** [awslabs/aws-iot-device-client#383]
**Is your feature request related to a problem? Please describe.**
I want to be able to specify a location for the .conf file.  "Does the following configuration appear correct? If yes, configuration will be written to /home/user/.aws-iot-device-client/aws-iot-device-client.conf: y/n
y"

**Describe the solution you'd like**
Is configuration correct? y 
Specify a location or use default location.

**Comment by xlcheng1** [comment]
Hello @monelgordillo , thank you for reaching out! If you would like to have a different location to store the configuration file, you can copy the completed .conf file into your desired location and start AWS IoT device client with `--config-file <your-path>` flag, here is the [detailed reference](https://github.com/awslabs/aws-iot-device-client/blob/main/docs/CONFIG.md#configuring-the-aws-iot-device-client).
