### ISSUE TITLE
setup "home" is hardcoded - does not apply to macos

### ISSUE THREAD

**Issue by monelgordillo** [awslabs/aws-iot-device-client#384]
**Describe the bug**

setup.sh has:

else
  OUTPUT_DIR=/**home**/$(whoami)/.aws-iot-device-client/
fi

This does not work for macos.

**Comment by xlcheng1** [comment]
Hello @monelgordillo , Unfortunately, AWS IoT device client does not support MacOS currently. Please refer to [List of Supported Platforms](https://github.com/awslabs/aws-iot-device-client#list-of-supported-platforms) for detailed information. Thank you!
