### ISSUE TITLE
"Received a multi-port tunnel request, but multi-port tunneling is not currently supported by Device client."

### ISSUE THREAD

**Issue by monelgordillo** [awslabs/aws-iot-device-client#385]
**Is your feature request related to a problem? Please describe.**
I am trying to run 2 services at once.  SSH and VNC.  I get this messaging on the device client side "Received a multi-port tunnel request, but multi-port tunneling is not currently supported by Device client."

**Describe the solution you'd like**
I would like to only use 1 json/tunnel for all the ports/services I need:

```
tunnel.json 
{
   "description": "Tunnel for test",
   "destinationConfig": { 
      "services": [ "SSH","VNC" ],
      "thingName": "Test-Ubuntu"
   },
   "tags": [ 
      { 
         "key": "Environment",
         "value": "Test"
      }
   ],
   "timeoutConfig": { 
      "maxLifetimeTimeoutMinutes": 720
   }
}
```

**Comment by xlcheng1** [comment]
Hello @monelgordillo , thanks for reaching out. Unfortunately Device Client currently does not have multi-tunneling support, but it is in our plan to implement, please be patient with us and check back later.
