### ISSUE TITLE
IoT policy when running device client + mqtt bridge

### ISSUE THREAD

**Issue by jlordiales** [awslabs/aws-iot-device-client#388]
Hi folks!

I have a fleet of devices where I want to run the device client for things like Jobs/Secure tunneling but I also have a local `mosquitto` broker that's publishing my application-specific messages to AWS using the [bridge functionality](https://aws.amazon.com/blogs/iot/how-to-bridge-mosquitto-mqtt-broker-to-aws-iot/).

The device client connects using the `thing-name` as the mqtt `clientID` so it means I can associate a restrictive [IoT policy](https://docs.aws.amazon.com/iot/latest/developerguide/iot-policies.html) to control what it's allowed to do (e.g., `"arn:aws:iot:<region>:<accountId>:topic/$aws/things/${iot:Connection.Thing.ThingName}/jobs/start-next"`).

Ideally I'd want to define similarly restrictive policies for the moquitto bridge to control which topics each device is able to publish messages to (e.g., `arn:aws:iot:us-east-1:123456789012:topic/${iot:Connection.Thing.Attributes[companyName]}/*`.

The issue I'm hitting is that those [thing policy variables](https://docs.aws.amazon.com/iot/latest/developerguide/thing-policy-variables.html) only work if the `clientID` matches the thing name. But the mosquitto bridge can't use that as the client id because it's already being used by the device client.

Are there any workarounds to get this working? Creating separate IoT things for the device client and the mosquitto bridge is the only alternative I could come up with but that feels... wrong.

I'd appreciate any suggestions.

Thank you!

**Comment by jlordiales** [comment]
Could I potentially point the device client to use the local mosquitto broker (so using `localhost:<port>` as the `--endpoint` config) and let the bridge handle all communication with AWS?

**Comment by HarshGandhi-AWS** [comment]
Hello @jlordiales , sorry for delay in response. 

Is it possible for you to use [MQTT Pub-Sub feature](https://github.com/awslabs/aws-iot-device-client/blob/main/source/samples/pubsub/README.md) for communicating with IoT core over MQTT? I believe that way you do not have to worry about (a) setting up MQTT broker and (2) creating different IoT thing/client ID. 

Let us know if this does not resolve the issue you are facing.

Regards,
Harsh Gandhi

**Comment by jlordiales** [comment]
Hey @HarshGandhi-AWS!
No, because I do need some of the more advanced features that a local mqtt broker like `mosquitto` provides.

For now I was able to work around this by triggering a lambda that will create and attach a second IoT Policy to the IoT Thing when it gets created. This second policy uses hardcoded values for the `clientID` and topics based on the Thing attributes.

It works but it's not ideal because those individual policies add extra maintenance costs over time

**Comment by HarshGandhi-AWS** [comment]
Hello @jlordiales, unfortunately that is the only workaround I can think of right now. I am glad that you were able to resolve the issue. You can also take a look at AWS IoT Fleet Provisioning feature for creating new policy while provisioning the device. [Fleet Provisioning Template](https://docs.aws.amazon.com/iot/latest/developerguide/provision-template.html) will work similar to Lambda but it is a better way for deploying production devices and maintaining them. 

Can you tell us which other advance features you are using which local mqtt broker like `mosquitto` provides? Maybe we can consider that as an enhancement to to provide in our [MQTT Pub-Sub sample feature](https://github.com/awslabs/aws-iot-device-client/blob/main/source/samples/pubsub/README.md).

**Comment by HarshGandhi-AWS** [comment]
It has been a while since we heard back from you. I am closing this issue now. Please feel free to reopen this issue or create a new issue if you face any difficulty using Device Client.
