### ISSUE TITLE
Possiblity to configure the location where the runtime-conf file and certificates after a fleet provisioning gets saved

### ISSUE THREAD

**Issue by ronit-wilson-r** [awslabs/aws-iot-device-client#390]
**Is your feature request related to a problem? Please describe.**
We have in our gateway a persistent partition, which is persistent across OTA updates(using mender). we would like to store the runtime-conf and the certificates from the fleet provisioning in this location.

**Describe the solution you'd like**
Have the path where the runtime-conf and the certificates saved as configurable

**Comment by HarshGandhi-AWS** [comment]
Hello @ronit-wilson-r , thank you for reaching out to us with this request. Please be patient with me until I discuss and evaluate this enhancement request with my team.

Regards, 
Harsh Gandhi

**Comment by HarshGandhi-AWS** [comment]
Also let us know if you are blocked with this issue or if the above mentioned workaround does not works for you.

**Comment by ronit-wilson-r** [comment]
Thank you for the information
