### ISSUE TITLE
googletest 1.13.0 requires C++14

### ISSUE THREAD

**Issue by thomas-roos** [awslabs/aws-iot-device-client#404]
**Describe the bug**
Yocto master release upgraded to googletest version 1.13.0, this version requires C++14 as a minimum.
(https://github.com/google/googletest/releases/tag/v1.13.0)
we use C++11: https://github.com/awslabs/aws-iot-device-client/blob/6633b3950182f1b1cd893c19d1dc1731b0eccd88/CMakeLists.txt#L140
But even when changing this to C++14 I get those errors!?: 
[error.log](https://github.com/awslabs/aws-iot-device-client/files/11138899/error.log)

**To Reproduce**
use yocto + meta-aws master branch

**Expected behavior**
build as it does with googletest version 1.12.1 (previous version on master branch)

**Environment (please complete the following information):**
 - OS: yocto
 - Version master
 - Architecture: all
 - Device Client commit: 1.8

**Comment by HarshGandhi-AWS** [comment]
Hey Thomas, we do not plan to upgrade the Cpp version right now. Will close this issue now and we can reopen it when we plan on upgrading the Cpp version. To unblock yourself, please downgrade the google-test lib version in yocto project to 1.12.0 which works with Cpp11.
