### ISSUE TITLE
greengrassv2 SecureTunnel component no longer compatible with Debian Stretch on armv7l

### ISSUE THREAD

**Issue by brianthelion** [awslabs/aws-iot-device-client#425]
**Describe the bug**

The SecureTunnel component recently stopped working for us on Debian Stretch on `armv7l`. Upon investigation, we found that this was due to a C++ ABI mismatch. Debian Stretch provides ABI version <= 1.3.10 and the component now requires ABI version == 1.3.11.

**To Reproduce**

1. (AWS console) Create a SecureTunnel deployment on a Debian Stretch `armv7l` device.
2. (AWS console) "Create a tunnel" to the target device.
3. (Device) `cat ${LOG_DIR}/aws.greengrass.SecureTunneling.log`
4. See error: (formatted for clarity)

```
{
  "thread": "Copier",
  "level": "INFO",
  "eventType": "stdout",
  "message": "[INFO ] 2023-09-16 21:34:46.346 [pool-3-thread-4] SubscribeResponseHandler - Secure tunnel process completed with exit code: 1",
  "contexts": {
    "scriptName": "services.aws.greengrass.SecureTunneling.lifecycle.run.script",
    "serviceName": "aws.greengrass.SecureTunneling",
    "currentState": "RUNNING"
  },
  "loggerName": "aws.greengrass.SecureTunneling",
  "timestamp": 1694900086355,
  "cause": null
}
```

**Expected behavior**

No `exit 1` message in logs; clients able to connect.

**Actual behavior**

```bash
set -ex
cd $(mktemp -d)
cp ${GG_ROOT}/v2/packages/artifacts/aws.greengrass.SecureTunneling/1.0.16/GreengrassV2SecureTunnelingComponent-1.0-all.jar ./
jar -xf GreengrassV2SecureTunnelingComponent-1.0-all.jar
cd aws.greengrass.SecureTunneling/linux/armv7l
chmod +x aws-iot-device-client
./aws-iot-device-client --help
```
gives

```
./aws-iot-device-client: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by ./aws-iot-device-client)
```

and

```
strings /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 | fgrep CXXABI
```

gives

```
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_1.3.8
CXXABI_1.3.9
CXXABI_1.3.10
CXXABI_TM_1
CXXABI_ARM_1.3.3
```

**Other context**

CI should be updated to compile with backwards compatibility for older ABI versions. Should be a simple change to `gcc` flags.

**Comment by HarshGandhi-AWS** [comment]
Hello @brianthelion , sorry for the delay in response. I was not aware of this issue with Debian and can try to reproduce and resolve the issue. 
Please be patient with us to work on reproducing and resolving it.

**Comment by brianthelion** [comment]
This issue is present on `v1.0.17` as well.

**Comment by HarshGandhi-AWS** [comment]
@brianthelion  Thank you for confirming that. Do you know from which version of the component you started seeing this issue?

**Comment by brianthelion** [comment]
We have tested down to v1.0.14 and they all suffer from the issue as described.

**Comment by HarshGandhi-AWS** [comment]
Hello @brianthelion , I was able to root cause the issue.

**Comment by HarshGandhi-AWS** [comment]
Hello @brianthelion , I was able to root cause the issue. Last year

**Comment by HarshGandhi-AWS** [comment]
Hello @brianthelion , I was able to root cause the issue. Last year we moved from Ubuntu 16 to Ubuntu 18 for building our binaries for doing Device Client build tests via CI. Few of these binaries are also used in Greengrass Secure Tunneling component. Since in Ubuntu 18, the version of libc, gcc and few other libraries used are not backward compatible, the cross compiled binary built for Secure Tunneling component on Ubuntu 18 are not working on the older operating systems. So far I have tested this on Ubuntu 16 and as expected I get the same error message which you have pasted above. One option to resolve this issue is to move back to Ubuntu 16 for building the binaries which is not an optimal solution since Ubuntu 16 has came to end of life and using it to build binaries might put us in a vulnerable state since it will not contain security patches and updated version of other dependency libraries. You have mentioned about using `gcc` flag, can you tell us more about it? Which flag are you suggesting us to use? Feel free to create a PR with your suggested change. Team can review it for you.

**Comment by brianthelion** [comment]
@HarshGandhi-AWS Can you please show me the repo where the build pipeline for the component lives? Thanks.

**Comment by HarshGandhi-AWS** [comment]
@brianthelion This code is responsible for building the arm7 device client binary for the secure tunneling component https://github.com/awslabs/aws-iot-device-client/blob/main/.github/build.sh#L92-L118

The code for creating the component is not yet opensource.

**Comment by HarshGandhi-AWS** [comment]
Also can you tell us the version of Debian OS your device is running on?

**Comment by brianthelion** [comment]
@HarshGandhi-AWS Debian Stretch.

**Comment by HarshGandhi-AWS** [comment]
Debian Stretch or Debian 9 has came to end of life last year in June. Because of this reason we cannot release a component for it. I am afraid you will either have to update the OS or build your own private component and use it until you migrate to a newer version of OS.

**Comment by brianthelion** [comment]
@HarshGandhi-AWS just to clarify, you are saying that the component is deprecated for older devices?

**Comment by HarshGandhi-AWS** [comment]
Yes. We would not be able to provide support for OS versions which came to end of life because of the reasons mentioned above.

**Comment by brianthelion** [comment]
@HarshGandhi-AWS please update the rePost.

**Comment by HarshGandhi-AWS** [comment]
I have added a comment on the re:post. 

I will close this issue now. Please feel free to create a new issue or [create a customer case]( https://aws.amazon.com/contact-us/) if you need more help from us. 

Thank you, 
Harsh Gandhi

**Comment by brianthelion** [comment]
This should be closed as WONTFIX.

**Comment by cmutzel** [comment]
hi @HarshGandhi-AWS - Just wanted to add a perspective here. I understand the cost to support old operating systems is high, but it seems wild to me that support would be silently dropped for a previously working OS without either a) a major version change for the component or b) a release note.  

We have been working with Greengrass for a while now and we continue to hit issues like these (missing/poor documentation, lack of complete support for basic use cases, lack of consideration of several pieces of the complete software development lifecycle build greengrass. These issues have been burning tons and tons of time for us and make it hard to believe that Greengrass should be our long term future.  

Again, understand the limitations of supporting older systems, but would appreciate more documentation/thought into these types of deprecations or changes to supported platforms in the future.

**Comment by HarshGandhi-AWS** [comment]
Hey @cmutzel I understand your concern and do understand the trouble you are going through with this issue. 

Unfortunately releasing a component which might have security issues is not something we should do. Regarding the major version release and a release note, we are working on it. I shared the concern over here first to inform you/our other customers as soon as possible. 

Again, as I mentioned earlier, we would be more than happy to help you build a private component until you are able to migrate to a newer OS version.

**Comment by brianthelion** [comment]
@HarshGandhi-AWS I don't think the "security issues" concern is valid in this case. This component is meant to be used by Greengrass developers for debugging while in development; it does NOT have a production use-case that I am aware of.

**Comment by MikeDombo** [comment]
Hi @brianthelion,

During development I would most likely not use this component, rather I would be developing either directly on the device or using standard ssh on my local network. The secure tunneling component is intended for production cases where physical access would not be possible.

**Comment by brianthelion** [comment]
@MikeDombo My point is that the component is only used by privileged developers and, therefore, the security concerns are negligible.

**Comment by MikeDombo** [comment]
The component is indended to be used by privileged developers you're absolutely right. This component does offer a path into devices, so security is paramount. Your OS vendor no longer supports the version you are using, it will not receive future security patches which could impact the security of this component.

I do understand your frustration. One solution you may choose is to use the dockerized version of this component available from our community. https://github.com/awslabs/aws-greengrass-labs-containerized-secure-tunneling
