### ISSUE TITLE
ST_COMPONENT_MODE build not working with a proxy

### ISSUE THREAD

**Issue by brnaba-aws** [awslabs/aws-iot-device-client#449]
**ST_COMPONENT_MODE build not working with a proxy**

When trying the use the aws-iot-device-client as a ST_COMPONENT_MODE (secure tunneling only), the http proxy configuration is compiled out and therefore not used.

**To Reproduce**

1. Build aws-iot-device-client in ST_COMPONENT_MODE 
2. Try to pass a proxy configuration
3. The proxy configuration is not used.

**Expected behavior**

in ST_COMPONENT_MODE, the proxy configuration should be applied.

**Actual behavior**

in ST_COMPONENT_MODE, the proxy configuration is not applied.

**Logs**

If applicable, add full logs of errors and outputs to help explain your problem. Preferably, you can also [increase the verbosity of the logs](https://github.com/awslabs/aws-iot-device-client#logging).

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04
 - Architecture: x86-64

**Additional context**

We used the https://github.com/awslabs/aws-greengrass-labs-containerized-secure-tunneling component to have the latest fix from the device client about secure tunneling with a proxy. Within the aws-greengrass-labs-containerized-secure-tunneling, the aws-iot-device-client is built using -DDISABLE_MQTT=ON flag. Defining this flag, removed the http proxy configuration we need for the secure tunneling part. We use the same flag as mentioned here: https://github.com/awslabs/aws-iot-device-client/blob/main/.github/build.sh#L90

**Comment by HarshGandhi-AWS** [comment]
Added couple of comments on the PR.
