### ISSUE TITLE
Device Client aborts on Red Hat Enterprise Linux ARM

### ISSUE THREAD

**Issue by matthewpaul** [awslabs/aws-iot-device-client#87]
While running the AWS IoT Device Client on a Red Hat Enterprise Linux instance with ARM processor, the Device Client aborted execution while running as a service due to a fatal error condition encountered in the AWS IoT v2 SDK for C++. The following is the error message reported via Systemd:

```
Fatal error condition occurred in /root/aws-iot-device-client/build/aws-iot-device-sdk-cpp-v2-src/crt/aws-crt-cpp/crt/aws-c-common/source/hash_table.c:619: entry >= &state->slots[0] && entry < &state->slots[state->size]
```

**Comment by HarshGandhi-AWS** [comment]
This issue is been resolved in the latest release of the Device Client.
